name: quizproject
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_lints: ^2.0.0
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.5


flutter:

  uses-material-design: true

  assets:
     - assets/img/
     - assets/
     - assets/img/icon.png

  fonts:
    - family: MN BURI
      fonts:
        - asset: assets/fonts/MN BURI.ttf
        - asset: assets/fonts/MN BURI Italic.ttf
        - asset: assets/fonts/MN BURI Bold.ttf
        - asset: assets/fonts/MN BURI Bold Italic.ttf

    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Medium.ttf
        - asset: assets/fonts/NotoSansThai-Regular.ttf


